config_version = 11

[bar.default]
background_opacity = 0.64999998547136784
center = [ "clock", "workspaces" ]
end = [ "tray", "notifications", "clipboard", "volume", "session" ]
margin_edge = 5
margin_ends = 600
padding = 30
position = "bottom"
start = [ "launcher", "wallpaper", "active_window" ]
thickness = 36

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 272.0
    box_width = 224.0
    cx = 3176.0
    cy = 200.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        circle = true
        clock_style = "analog"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 336.0
    box_width = 352.0
    cx = 264.0
    cy = 242.0
    output = "DP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bar_width = 0.59999999999999998
        bloom_intensity = 0.5
        fade_when_idle = true
        inner_diameter = 0.69999999999999996
        primary_color = "primary"
        ring_opacity = 0.80000000000000004
        rotation_speed = 0.5
        secondary_color = "secondary"
        sensitivity = 1.5
        visualization_mode = "wave_rings"
        wave_thickness = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 3180.0
    cy = 368.0
    output = "DP-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        display = "graph"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 112.0
    box_width = 176.0
    cx = 3178.0
    cy = 498.0
    output = "DP-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = false
        stat = "gpu_usage"
        stat2 = "gpu_temp"

[dock]
auto_hide = true
background_opacity = 0.64999998547136784
enabled = true
icon_size = 30
launcher_position = "start"
magnification_scale = 1.0
reserve_space = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 1720.0
    cy = 1241.5
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[notification]
background_opacity = 0.48999998904764652

[osd]
background_opacity = 0.4999999888241291

[shell]
panel_anchor_bar = "default"
polkit_agent = true
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    open_near_click_control_center = true
    transparency_mode = "glass"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
source = "wallpaper"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[widget.workspaces]
label_source = "name"
max_label_chars = 9
